version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: password

  app:
    build: .
    ports:
      - "3000:3000"
    container_name: nestjs-app
    depends_on:
      - rabbitmq
    environment:
      DATABASE_URL: "file:./dev.db"
      RABBITMQ_URL: "amqp://rabbitmq:5672"
    volumes:
      - .:/usr/src/app
    command: npm run start:dev